import { ACCOUNT_DELETION_GRACE_DAYS } from '@/lib/constants';
import { LEGAL_ENTITY } from './config';

const { brand, operatorName, country, privacyEmail, contactEmail } = LEGAL_ENTITY;

export const PRIVACY = `
## 1. Scope

This policy explains what personal data ${brand} collects, why, how long we keep
it, and what you can do about it. It covers both the EU/UK General Data Protection
Regulation (GDPR) and Turkish Law No. 6698 on the Protection of Personal Data
(KVKK).

## 2. Who is responsible

${operatorName}, established in ${country}, is the **data controller** (KVKK: *veri
sorumlusu*) for the data described here. You can reach us about anything in this
policy at ${privacyEmail}.

### 2.1 Controller and processor, and why the distinction matters here

For your account, billing, and platform usage data we are the controller: we
decide why and how it is processed.

For the content you feed to a model — your prompts, your uploaded documents, the
outputs agents produce — we act as a **processor on your instructions**. You
choose which model provider to call by connecting your own key. When an agent
sends your prompt to OpenAI, Anthropic, or Google, it does so because you
configured it to. Those providers are independent controllers or processors under
their own terms, which you accepted when you obtained your key.

## 3. What we collect

### 3.1 Data you give us

| Data | Why we hold it |
| --- | --- |
| Email address | To identify your account, sign you in, and contact you about the Service |
| Password | Stored only as an Argon2 hash. We never see your password |
| Display name (optional) | To personalise the interface |
| Model provider API keys | To call the providers you chose, on your behalf. Encrypted with AES-256-GCM; never returned to the browser |
| Prompts, task history, agent outputs | To run your tasks and show you their results |
| Uploaded documents | To ground agent answers in your own material (retrieval) |
| Custom agent configurations | To let you build and reuse agent teams |
| Card brand, last four digits, expiry | To show you which card is on file |

**We never store your full card number.** It exists only in memory for the
duration of a single call to the payment processor and is never written to a
database, a log, or an API response.

### 3.2 Data generated by using the Service

- **Usage records** — tokens consumed per task, the provider used, and whether the
  task succeeded. This is how quota is enforced and how your dashboard is built.
- **Agent logs** — the step-by-step trace of a task, so you can inspect what your
  agents did in the Architect view.
- **Conversation memory and document embeddings** — vector representations of your
  prior conversations and documents, so agents can recall relevant context. These
  are scoped to your user id and are never searchable by another user.

### 3.3 What we do not collect

We run no analytics, no advertising, and no third-party tracking. We do not build
a profile of you. We do not sell personal data, and we never have. We do not use
your content to train models.

## 4. Legal bases (GDPR Art. 6 / KVKK Art. 5)

| Purpose | GDPR basis | KVKK basis |
| --- | --- | --- |
| Providing the Service you asked for | Performance of a contract | Necessary for the performance of a contract |
| Taking payment, preventing fraud | Performance of a contract; legitimate interests | Necessary for a contract; legitimate interests |
| Keeping the platform secure, preventing abuse | Legitimate interests | Legitimate interests |
| Meeting tax, accounting and legal duties | Legal obligation | Explicitly provided for by law |
| Answering your support requests | Legitimate interests | Legitimate interests |

Where we rely on legitimate interests, we have weighed them against your rights
and freedoms and concluded they do not override them. You may object — see
section 8.

## 5. Who we share it with

We share personal data only with the processors below, and only as far as each
needs it to do its job. We do not sell your data, and we do not disclose it to
advertisers.

### 5.1 Subprocessors

| Subprocessor | What it does | Data it sees |
| --- | --- | --- |
| Model providers you connect (OpenAI, Anthropic, Google, or others) | Runs the inference your agents request | The prompts, context, and documents your agents send |
| Our hosting and database infrastructure | Runs the application and stores its data | All data stored by the Service, at rest |
| Payment processor | Takes payment for subscriptions | Your card details and billing identifiers |

Model providers are engaged **by you**, through the key you connected. If you use
only the local free tier, no prompt of yours leaves our infrastructure.

We will publish material changes to this list before they take effect.

### 5.2 Other disclosures

We may disclose personal data where we are legally compelled to, where it is
necessary to establish or defend a legal claim, or where there is an imminent risk
to someone's safety. If we are compelled to disclose your data we will tell you,
unless we are legally barred from doing so.

### 5.3 Business customers

If you need a Data Processing Agreement, write to ${privacyEmail} and we will
provide one.

## 6. International transfers

We are established in ${country}. When your agents call a model provider located
elsewhere — most are in the United States — your prompt is transferred there. That
transfer happens because you configured that provider.

Where we transfer personal data out of the EEA, the UK, or ${country} as a
controller, we rely on an adequacy decision where one exists, and otherwise on
Standard Contractual Clauses or the equivalent KVKK undertaking.

## 7. How long we keep it

| Data | Retention |
| --- | --- |
| Account, subscription, API key records | Until you delete your account |
| Task sessions and agent logs | Automatically expire after the platform's retention window, or sooner if you delete your account |
| Conversation memory, document chunks | Until you delete the document, or delete your account |
| Usage records | Until you delete your account |
| Invoicing and tax records | For as long as tax and accounting law requires, even after account deletion |

### 7.1 Deleting your account

You can request deletion at any time from your profile settings. When you do:

1. Your account is **locked immediately**. You cannot start tasks, spend quota, or
   use any part of the product. A paid subscription is cancelled so you are not
   billed again.
2. For **${ACCOUNT_DELETION_GRACE_DAYS} days** you may sign in and restore the
   account. This grace period exists so that an accidental or malicious deletion
   is recoverable. Restoring does not reinstate a cancelled subscription.
3. After ${ACCOUNT_DELETION_GRACE_DAYS} days, everything is **permanently and
   irreversibly erased**: your account row and everything cascading from it (API
   keys, subscription, payment method, usage records), your task sessions, agent
   logs, documents, and custom agents, and your conversation memories and document
   embeddings in the vector store.

Agent teams you published to the Marketplace are an exception. They are **not**
deleted, because other users have installed them. Instead we sever the link
between the item and you: the author identifier is removed and the item becomes
attributable only to "Community". The content itself is no longer personal data
about you. If a published item contains personal data you typed into it, tell us
at ${privacyEmail} and we will remove the item.

Before the purge, you can download everything we hold about you as a JSON file
from your profile settings.

## 8. Your rights

Under the GDPR you have the right to access your data (Art. 15), to have it
corrected (Art. 16), to have it erased (Art. 17), to restrict processing
(Art. 18), to data portability (Art. 20), and to object to processing based on
legitimate interests (Art. 21).

Under KVKK Art. 11 you have the right to learn whether your personal data is
processed, to request information about it, to learn its purpose and whether it is
used accordingly, to know the third parties it is transferred to, to have
incomplete or inaccurate data corrected, to request its erasure or destruction, to
have corrections and erasures notified to those third parties, to object to a
result produced solely by automated analysis, and to claim compensation for damage
caused by unlawful processing.

Most of these you can exercise yourself: the profile settings page lets you edit
your data, export all of it, and delete your account. For anything else, write to
${privacyEmail}. We will respond within one month (GDPR) and within thirty days
(KVKK). We will not charge you unless a request is manifestly unfounded or
excessive.

You may lodge a complaint with your local supervisory authority. In ${country} that
is the Personal Data Protection Authority (**KVKK — Kişisel Verileri Koruma
Kurumu**). In the EEA it is the authority of the country where you live.

## 9. Security

Passwords are hashed with Argon2. Provider API keys are encrypted with AES-256-GCM
under a master key held outside the codebase, and are never sent to the browser.
Every query for your data is filtered by your user id, so one account's memory
cannot surface in another's. Code that agents execute runs in an isolated sandbox.

Read the [Security page](/security) for the detail. No system is perfectly secure;
if you believe you have found a vulnerability, write to ${contactEmail}.

## 10. Automated decision-making

We do not make decisions that produce legal or similarly significant effects about
you by automated means. Agents generate content on your instruction; they do not
decide anything about you.

## 11. Children

The Service is not directed at children and we do not knowingly collect their
data. If you believe a child has given us personal data, write to ${privacyEmail}
and we will delete it.

## 12. Changes

We will announce material changes to this policy in the product or by email before
they take effect. The date at the top of this page always reflects the current
version.

## 13. Contact

Privacy and data-subject requests: ${privacyEmail}
`.trim();
